# Generated by Django 3.2.14 on 2022-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans_code', models.CharField(max_length=50, null=True, verbose_name='计划代码/编号（编码规则迎合质控要求）')),
                ('plans_name', models.CharField(max_length=255, null=True, verbose_name='计划名称')),
                ('plans_begindate', models.DateTimeField(null=True, verbose_name='计划开始时间')),
                ('plans_enddate', models.DateTimeField(null=True, verbose_name='计划结束时间（预设）')),
                ('complete_date', models.DateTimeField(null=True, verbose_name='实际完工时间')),
                ('target_datanumber', models.CharField(max_length=50, null=True, verbose_name='目标数据量（可能是例，可能是张）')),
                ('target_accuracy', models.CharField(max_length=50, null=True, verbose_name='目标准确率')),
                ('plan_usernumber', models.CharField(max_length=50, null=True, verbose_name='计划参与人数')),
                ('algorithm_code', models.CharField(max_length=50, null=True, verbose_name='对应算法版本编号')),
                ('algorithm_accuracy', models.CharField(max_length=50, null=True, verbose_name='算法准确率')),
                ('current_state', models.IntegerField(choices=[('0', '未开始'), ('1', '进行中'), ('2', '暂停'), ('3', '挂起'), ('4', '完成')], null=True, verbose_name='当前状态(未开始、进行中、暂停、挂起、完成)')),
                ('remarks', models.CharField(max_length=500, null=True, verbose_name='备注、描述')),
                ('createuserid', models.IntegerField(null=True, verbose_name='创建人ID')),
                ('modifyuserid', models.IntegerField(null=True, verbose_name='修改人ID')),
                ('freezeuserid', models.IntegerField(null=True, verbose_name='冻结计划的用户id')),
                ('freezeflag', models.IntegerField(null=True, verbose_name='冻结标记 0 未冻结 1 冻结')),
                ('freezedate', models.CharField(max_length=50, null=True, verbose_name='冻结时间')),
                ('freezesavepath', models.CharField(max_length=255, null=True, verbose_name='冻结数据保存路径')),
            ],
            options={
                'verbose_name': '计划表',
                'db_table': 'plans',
            },
        ),
    ]
