# Generated by Django 3.2.14 on 2022-08-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('received_time', models.DateTimeField(verbose_name='Received time')),
                ('data_batch_number', models.CharField(max_length=128, unique=True, verbose_name='Data batch number')),
                ('data_resource', models.CharField(max_length=64, verbose_name='Data resource')),
                ('case_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of cases')),
                ('image_number', models.PositiveIntegerField(verbose_name='Number of images')),
                ('verify_status', models.CharField(choices=[('waiting', '待评审'), ('running', '评审中'), ('passed', '评审通过'), ('fail', '评审不通过')], db_index=True, max_length=64, verbose_name='Verify status')),
                ('pretreatment_status', models.CharField(choices=[('waiting', '待评审'), ('running', '评审中'), ('passed', '评审通过'), ('fail', '评审不通过')], db_index=True, max_length=64, verbose_name='pretreatment status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('blind_number', models.CharField(max_length=128, unique=True, verbose_name='Blind number')),
                ('image_name', models.CharField(max_length=128, verbose_name='Image name')),
                ('original_case_number', models.CharField(max_length=128, unique=True, verbose_name='original case number')),
                ('batch', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_annotation.databatch', to_field='data_batch_number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
