# Generated by Django 3.2.14 on 2022-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
                ('status', models.PositiveSmallIntegerField(choices=[('1', '启用'), ('0', '禁用')], default=1, verbose_name='状态')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目目标')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUserRelation',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.PositiveSmallIntegerField()),
                ('user_id', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('leader', '项目负责人'), ('member', '项目成员')], default='member', max_length=16, verbose_name='用户在项目中的级别')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
