# Generated by Django 3.2.14 on 2022-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBmanageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans_tablename', models.CharField(max_length=50, verbose_name='当前使用数据表名')),
            ],
            options={
                'verbose_name': '数据路由表',
                'db_table': 'db_manage',
            },
        ),
    ]
